#!/bin/sh

# Dependency: grep, curl, exiftool, xclip/xsel/pbcopy

# Variable explain:
# $y: the current argument
# $pos: the current position on argument y
# $y2: the final position (invert color using SGR 33 7)
# $num: numbers of lines per argument
# $fin: bottom for printable area, depends on num
# $token: indicator for actions
# Dimension is adjustable by $top & $bottom


# Stolen from shfm
# Reference: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences
esc() {
    case $1 in
        # vt100 (IL is vt102) (DECTCEM is vt520)
	CUP)     printf '%s[%s;%sH' "$esc_c" "$2" "$3" ;; # cursor to LINES($2), COLUMNS($3)
        CUU)     printf '%s[%sA'    "$esc_c" "$2"      ;; # cursor up
        CUD)     printf '%s[%sB'    "$esc_c" "$2"      ;; # cursor down
        CUR)     printf '%s[%sC'    "$esc_c" "$2"      ;; # cursor right
	CUL)     printf '%s[%sD'    "$esc_c" "$2"      ;; # cursor left
	DECAWM)  printf '%s[?7%s'   "$esc_c" "$2"      ;; # (h: set; l: unset) line wrap
        DECRC)   printf '%s8'       "$esc_c"           ;; # cursor restore
        DECSC)   printf '%s7'       "$esc_c"           ;; # cursor save
        DECSTBM) printf '%s[%s;%sr' "$esc_c" "$2" "$3" ;; # scroll region
	DECTCEM) printf '%s[?25%s'  "$esc_c" "$2"      ;; # (h: show; l: hide) cursor visible
	ED[0-2]) printf '%s[%sJ'    "$esc_c" "${1#ED}" ;; # clear screen
        EL[0-2]) printf '%s[%sK'    "$esc_c" "${1#EL}" ;; # clear line
        IL)      printf '%s[%sL'    "$esc_c" "$2"      ;; # insert line
        SGR)     printf '%s[%s;%sm' "$esc_c" "$2" "$3" ;; # colors

        # xterm (since 1988, supported widely)
	screen_alt) printf '%s[?1049%s' "$esc_c" "$2" ;; # (h: to; l: back from) alternate buffer
    esac
}

get_os() {
    case $OSTYPE in
	darwin*) BIB_OPENER=open; clipcopy=pbcopy ;;
	*) { command -v xclip 1> /dev/null 2>&1 && clipcopy=xclip; } || { command -v xsel 1> /dev/null 2>&1 && clipcopy=xsel; } ;;
    esac
}

term_setup() {
    num=$1; shift
    # space for status_line
    bottom=$((LINES - 2))
    top=3
    fin=$(( bottom - (bottom - (top - 1)) % num ))

    stty=$(stty -g)
    stty -icanon -echo
    esc screen_alt h
    esc DECAWM l
    esc DECTCEM h
    esc ED2
    esc DECSTBM "$top" "$fin"
}

term_resize() {
    # false-positive, behavior intentional, globbing is disabled.
    # shellcheck disable=2046
    {
        set -f -- $(stty size)
        set +f
    }

    LINES=$1 COLUMNS=$2
}

term_reset() {
    esc DECAWM h     >&2
    esc DECTCEM h    >&2
    esc ED2          >&2
    esc DECSTBM      >&2
    esc screen_alt l >&2
    stty "$stty"
}

redraw() {
    num=$1; shift
    list_print "$num" "$@"
    status_line 't'
    status_line 'b' "$#"
}

list_print() {
    num=$1; shift
    esc ED2
    esc CUP "$top"

    i=1
    pos=$(( num * y - num + top ))
    end=$(( fin + 1 ))
    mid=$(( end / 4 < 5 ? 1 : end / 4 ))
    case $hist in
        2) # redraw after cmd run
            shift "$((y > y2 ? y - y2 : 0))"
        ;;

        1) # redraw after go-to-parent
            hist_search "$@"
            shift "$((y >= fin ? y - mid : 0))"
        ;;

        *) # everything else
	    shift "$((y >= (end - top) / num ? y - (end - top) / num : 0 ))"
        ;;
    esac

    for file do

	# same formula as $pos
	case $(( num * i - num + top )) in
	    $y2) esc SGR 33 7 ;;
	esac

	case $(( num * i - num + top - end )) in
	    -*)
		arg_format "$file"
		esc CUD
		;;
	esac
	i=$((i + 1))
    done

    esc CUP "$(( pos > y2 ? y2 : pos ))"
}

arg_print() {
    offset=$1

    case $offset in
        "$y") esc SGR 33 7
    esac

    shift "$offset"

    case $offset in
        "$y") cur=$1
    esac

    arg_format "$1"
}

arg_format() { # token
    esc EL0
    case "$token" in
	's'|'r') printf %s "${1%$nl}" ;;
	'?'|'q') printf %s "$1" ;;
        ''|'p') printf %s "${1##*/}" ;;
    esac
    esc SGR
    printf '\r'
}

status_line() {
    caption=$1; shift
    esc DECSC
    case "$caption" in
	't') esc CUP 1 ;;
	'b') esc CUP "$LINES" ;;
    esac

    case $USER in
        root) esc SGR 31 7 ;;
           *)
	       case "$caption" in
	           't') esc SGR 36 7 ;;
		   'b') esc SGR 34 7 ;;
	       esac
	       ;;
    esac

    case "$caption" in
        't')
	    printf '%*s\r' "$COLUMNS"
	    case $msg in
	        '') printf %s "Reference" ;;
		*) printf %s "$msg" ;;
	    esac
	    ;;
	'b')
	    printf '%*s\r%s ' "$COLUMNS" "" "($y/$1)"
	    case $ltype in
		'') printf %s "$BIB_PDF_PATH" ;;
		*) printf %s "$ltype" ;;
	    esac
    esac
    esc SGR
    esc DECRC
}

term_scroll_up() {
    num=$1; shift

    case $y in
        -*|0|1) return ;;
    esac

    y=$((y - 1))

    arg_print "$((y + 1))" "$@"

    case "$y2" in
	$top) [ $num -gt 1 ] && esc CUU $((num - 1)); esc IL "$num" ;;
	*) esc CUU "$((num * 2 - 1))"; y2=$(( y2 > top ? y2 - num : top )) ;;
    esac
    arg_print "$y" "$@"

    # Restore cursor to match y2
    [ $num -gt 1 ] && esc CUU "$((num - 1))"
    status_line 't'
    # status_line 'b' "$y2"
    status_line 'b' "$#"
}


term_scroll_down() {
    num=$1; shift

    case $((y - $#)) in
	[0-9]*) return
    esac

    y=$((y + 1))  pos=$(( num * y - num + top ))
    y2=$(( pos < fin - (num - 1) ? pos : fin - (num - 1) ))

    arg_print "$((y - 1))" "$@"
    printf '\n'
    arg_print "$y" "$@"

    [ $num -gt 1 ] && esc CUU "$((num - 1))"

    status_line 't'
    # status_line 'b' "$y2"
    status_line 'b' "$#"
}

prompt() {
    esc DECSC
    esc CUP "$LINES"
    printf %s "$1"
    esc DECTCEM h
    esc EL0

    case $2 in
        r)
            stty icanon echo 1>/dev/null 2>&1
            read -r ans ||:
            stty -icanon -echo
        ;;
    esac

    esc DECRC
    esc DECTCEM l
    status_line 'b' "($y/$#) $PWD"
}

cmd_run() {
    stty "$stty"
    esc DECTCEM h
    esc DECSTBM
    esc ED2
    "$@" ||:
    esc DECSTBM "$top" "$((LINES - 2))"
    esc DECTCEM l
    stty -icanon -echo
    hist=2
}

ref_search() {
    tmplist= list=
    str=$ans
    url=
    while c=${str%"${str#?}"}; do
	case $c in
	    '') break ;;
	    [[:space:]]) url=$url\+ ;;
	    *)           url=$url$c ;;
	esac

	str=${str#?}
    done

    case "$url" in
        '') return 2 ;;
	*)
	    ltype="Searching..."
	    status_line 'b' "$#"
	    html="$(curl -s "https://search.crossref.org/?q=$url")"
	    case "$html" in
		*'Service Unavailable'*) return 1 ;;
		*)
		    IFS="$nl"
		    set -- $html
		    unset IFS

		    for line do
			case $line in
			    *Author*)
				tmp=${line#\<p\ class=\'expand\'\>Authors:\ }
				tmplist="$tmplist${nl}${tab}Author(s): ${tmp%\<\/p\>}"
				;;
			    'published')
				tmp=${preline#\<b\>}
				tmplist="$tmplist${nl}${tab}Category: ${tmp%\<\/b\>}"
				;;
			    [0-9][0-9][0-9][0-9]) tmplist="$tmplist${nl}${tab}Year: $line";;
			    https\:\/\/doi.org\/*|https\:\/\/dx.org\/*) tmplist="$tmplist${nl}${tab}Doi: $line" ;;
			esac
			case $preline in
			    'in')
				tmp=${line#\<b\>}
				tmplist="$tmplist${nl}${tab}Journal: ${tmp%\<\/b\>}"
				;;
			    \<p\ class=\'lead\'\>) tmplist="$tmplist${nl}|$line" ;;
			esac

			preline="$line"
		    done

		    # Add \n if some entry does not have 6 lines
		    IFS='|'
		    set -- $tmplist; shift
		    unset IFS

		    # Each item must have totally 6 \n
		    for line do
			case $line in
			    *${nl}*${nl}*${nl}*${nl}*${nl}*${nl}) list="$list|$line" ;;
			    *${nl}*${nl}*${nl}*${nl}*${nl}) list="$list|$line${nl}" ;;
			    *${nl}*${nl}*${nl}*${nl}) list="$list|$line${nl}${nl}" ;;
			    *${nl}*${nl}*${nl}) list="$list|$line${nl}${nl}${nl}" ;;
			    *${nl}*${nl}) list="$list|$line${nl}${nl}${nl}${nl}" ;;
			    *${nl}) list="$list|$line${nl}${nl}${nl}${nl}${nl}" ;;
			    *${nl}*${nl}*${nl}*${nl}*${nl}*) list="$list|$line${nl}" ;; # match last item
			    *${nl}*${nl}*${nl}*${nl}*) list="$list|$line${nl}${nl}" ;; # match last item
			    *${nl}*${nl}*${nl}*) list="$list|$line${nl}${nl}${nl}" ;; # match last item
			    *${nl}*${nl}*) list="$list|$line${nl}${nl}${nl}${nl}" ;; # match last item
			    *${nl}*) list="$list|$line${nl}${nl}${nl}${nl}${nl}" ;; # match last item
			esac
		    done
		    list=${list#*|}
		    ;;
	    esac
    esac
}

ref_gen() {
    tmplist= list=
    IFS="$nl"
    set -- $(cat -u $BIB)
    unset IFS
    for line do
	case $line in
	    @*)
		tmp="${line##*\{}"
		tmplist="$tmplist${nl}|BibTeX: ${tmp%,}"
		;;
	    *[[:space:]]title*=*)
		tmp="${line#*\{}"
		tmplist="$tmplist${nl}${tab}Title: ${tmp%\}*}"
		;;
	    *[[:space:]]author*=*)
		tmp="${line#*\{}"
		tmplist="$tmplist${nl}${tab}Author(s): ${tmp%\}*}"
		;;
	    *[[:space:]]year*)
		tmp="${line#*=}"
		tmp="${tmp#\{}"
		tmp=${tmp%,}
		tmp=${tmp%\}}
		tmplist="$tmplist${nl}${tab}Year: $tmp"
		;;
	    *[[:space:]]journal*=*)
		tmp="${line#*\{}"
		tmplist="$tmplist${nl}${tab}Journal: ${tmp%\}*}"
		;;
	esac
    done

    IFS='|'
    set -- $tmplist; shift
    unset IFS

    for line do
	case $line in
	    *${nl}*${nl}*${nl}*${nl}*${nl}) list="$list|$line" ;;
	    *${nl}*${nl}*${nl}*${nl}) list="$list|$line${nl}" ;;
	    *${nl}*${nl}*${nl}) list="$list|$line${nl}${nl}" ;;
	    *${nl}*${nl}) list="$list|$line${nl}${nl}${nl}" ;;
	    *${nl}) list="$list|$line${nl}${nl}${nl}${nl}" ;;
	    *${nl}*${nl}*${nl}*${nl}*) list="$list|$line${nl}" ;; # match last item
	    *${nl}*${nl}*${nl}*) list="$list|$line${nl}${nl}" ;; # match last item
	    *${nl}*${nl}*) list="$list|$line${nl}${nl}${nl}" ;; # match last item
	    *${nl}*) list="$list|$line${nl}${nl}${nl}${nl}" ;; # match last item
	esac
    done
    list=${list#*|}
}

restore() {
    num=1 y=1 y2=$top cur=$1 ltype= msg= token=
    term_setup $num
    redraw $num "$@"
}

yesno() {
    msg=$1 item=$2 token_q=$3 shift 3
    num=1 y=1 y2=$top cur=$1 ltype= token=q
    redraw $num "$@"

    esc DECSC
    esc CUP $((top - 1 + 5))
    printf %s "$item"
    esc DECRC
}

filter() {
    format="$2" IFS="$3"
    set -- $1
    for line do
	eval "$format"; tmp2=${tmp##*$ans}
	case $(( ${#tmp} - ${#tmp2} )) in
	    0) shift ;;
	    *) filter="$filter$IFS$tmp" ;;
	esac
    done
    filter=${filter#*$IFS}
    unset IFS
}

waitclip() {
    case "$clipcopy" in
	"pbcopy") clipcmd="pbcopy" ;;
	"xclip") clipcmd="xclip -selection clipboard"; printf '%s' "" | xclip -selection clipboard ;;
	"xsel") clipcmd="xsel --clipboard"; xsel -bc ;;
    esac
    count=1 countlimit=3600
    while :; do
	set -- "Copy BibTeX within $countlimit second; Already $count second past. Press h to cancel"
	num=1 y=1 y2=$top cur=$1 ltype= msg="Google Scholar Search" token=
	redraw 1 "$@"
	clip="$(printf '%s' "$clipcmd" | ${SHELL:-"/bin/sh"})"
	count=$((count + 1))
	case $count in
	    $countlimit) break ;;
	esac
	case $key${esc:=0} in
	    h?|D2|"$bs_char"?) break ;;
	    "$esc_c"*) esc=1 ;;
	    '[1') esc=2 ;;
	    *) esc=0 ;;
	esac
	sleep 1
	case $clip in
	    '') continue ;;
	    *) break ;;
	esac
    done
    unset count
}

key() {
    while key=$(dd ibs=1 count=1 2>/dev/null); do
	case $key${esc:=0} in
	    k?|A2) # token
		case "$token" in
		    's') num=6 ;;
		    'r') num=5 ;;
		    ''|'?'|'q'|'p') num=1 ;;
		esac
		term_scroll_up $num "$@"
	    ;;

            j?|B2) # token
		case "$token" in
		    's') num=6 ;;
		    'r') num=5 ;;
		    ''|'?'|'q'|'p') num=1 ;;
		esac
		term_scroll_down $num "$@"
	    ;;

            l?|C2|"$esc") # ARROW RIGHT # token
		case "$token" in
		    'q')
			case "$cur" in
			    "Yes")
				case "$token_q" in
				    'sc')
					grep "${bibtex%%$nl*}" "$BIB"
					case $? in
					    0)
						set -- 'Reference already added; press h to leave'
						num=1 y=1 y2=$top cur=$1 ltype= msg="Result" token=
						redraw $num "$@"
						;;
					    *)
						printf '%s\n\n' "$bibtex" >> "$BIB"
						set -- "Reference added to $BIB; press h to leave"
						num=1 y=1 y2=$top cur=$1 ltype= msg="Result" token=
						redraw $num "$@"
						;;
					esac
					;;
				    'sg')
					cmd_run "${BIB_OPENER:=xdg-open}" "https://scholar.google.com/scholar?&q=$ans"
					waitclip
					;;
				esac
				;;
			    "No")
				set -- $BIB_PDF_PATH/*.pdf
				restore "$@"
				;;
			    *)
				case "$token_q" in
				    'p')
					ans=${cur##* : }
					ans=${ans##*doi.org/}
					ans="${ans%%$nl*}"
					case "$ans" in
					    10\.[0-9][0-9][0-9][0-9]\/[^[:space:][:cntrl:]]*) # match doi
						bibtex=$(curl -s "http://api.crossref.org/works/$ans/transform/application/x-bibtex")
						set -- 'Yes' \
						       'No'
						yesno "Copy bibtex to $BIB?" "$bibtex" 'sc' "$@"
						;;
					    *)
						ref_search "$@"
						case $? in
						    1) set -- 'Fail to connect to Crossref'; num=1 token= ;;
						    0)
							IFS='|'
							set -- $list
							unset IFS
							num=6 y=1 y2=$top cur=$1 ltype="Search: $ans" msg="Search by text" token=s
							;;
						esac
						term_setup $num
						redraw $num "$@"
						;;
					esac
					;;
				esac
				;;
			esac
			;;
		    's')
			case $cur in
			    "$gscholar")
				cmd_run "${BIB_OPENER:=xdg-open}" "https://scholar.google.com/scholar?&q=$ans"
				waitclip
				;;
			    *)
				ans=${cur##*: }
				ans=${ans##*doi.org/}
				ans="${ans%%$nl*}"
				bibtex=$(curl -s "http://api.crossref.org/works/$ans/transform/application/x-bibtex")

				set -- 'Yes' \
				       'No'
				yesno "Copy bibtex to $BIB?" "$bibtex" 'sc' "$@"
				;;
			esac
			;;
		    'r')
			ans=${cur%%$nl*}
			ans=${ans##*BibTeX: }
			case "$clipcopy" in
			    "pbcopy") printf '%s' "$ans" | pbcopy ;;
			    "xclip") printf '%s' "$ans" | xclip -selection clipboard ;;
			    "xsel") printf '%s' "$ans" | xsel --clipboard ;;
			esac
			set -- "$ans has copied to clipboard using $clipcopy; press h to leave"
			num=1 y=1 y2=$top cur=$1 ltype= msg="Result" token=
			redraw $num "$@"
			;;
		    'p')
			case "$(dd if="$1" count=4 bs=1)" in
			    '%PDF') info=$(exiftool $cur) ;;
			    *) info='PDF file is broken, or not choosing PDF file; press h to leave' ;;
			esac
			IFS="$nl"
			set -- $info
			unset IFS
			num=1 y=1 y2=$top cur=$1 ltype= msg='Search by which information?' token=q token_q=p
			redraw $num "$@"
			;;
		    '')
			[ -e "$cur" ] &&
			    {
				cmd_run "${BIB_OPENER:="${READER:=xdg-open}"}" "$cur"
				redraw 1 "$@"
			    }
			;;
		    '?') ;;
		esac
            ;;

            h?|D2|"$bs_char"?) # ARROW LEFT
		set -- $BIB_PDF_PATH/*.pdf
		restore "$@"
            ;;

	    s?)
		gscholar="There is no matching...\\(ㄒoㄒ)/${nl}${tab}Search in Google Scholar!${nl}${nl}${nl}${nl}${nl}"
		prompt "Search in Crossref: " r
		ref_search "$@"
		# list=$(cat -u /home/huijunchen/Testing/output)
		case $? in
		    2) set -- 'type something'; num=1 cur=$1 ltype="Error!" msg="Error messege: " token= ;;
		    1)
			set -- 'Yes' \
			      'No'
			yesno "Fail to connect Crossref. Search in Google scholar?" "" 'sg' "$@"
			;;
		    0)
			IFS='|'
			set -- $list \
			       "$gscholar"
			unset IFS
			num=6 y=1 y2=$top cur=$1 ltype="search: $ans" msg="search by text" token=s
			;;
		esac
		term_setup $num
		redraw $num "$@"
	    ;;

	    p?)
		set -- $BIB_PDF_PATH/*.pdf
		num=1 y=1 y2=$top cur=$1 ltype= msg='Search by information in PDF' token=p
		redraw $num "$@"
	    ;;

	    r?)
		ref_gen "$@"

		IFS='|'
		set -- $list
		unset IFS
		num=5 y=1 y2=$top cur=$1 ltype="Search BibTeX Entry" msg="Choose which BibTeX Entry?" token=r
		term_setup $num
		redraw "$num" "$@"
	    ;;

            g?) # token
                case $y in
                    1) continue ;;
                esac

		case "$token" in
		    's') num=6 ;;
		    'r') num=5 ;;
		    ''|'?'|'q'|'p') num=1 ;;
		esac
                y=1 y2=$top cur=$1
		redraw "$num" "$@"
            ;;

            G?) # token
		case "$token" in
		    's') num=6 ;;
		    'r') num=5 ;;
		    ''|'?'|'q'|'p') num=1 ;;
		esac
		y=$# pos=$(( num * y - (num - 1) + (top - 1) ))
		y2=$(( pos < fin - (num - 1) ? pos : fin - (num - 1) ))
		cur=$($#)
		redraw "$num" "$@"
            ;;

            /?) # token
                prompt / r

		case "$token" in
		    ''|'p')
			num=1
			filter "$BIB_PDF_PATH/*.pdf" 'tmp=$line' "$nl"
			IFS="$nl"
			set -- $filter
			unset IFS filter
			;;
		    's'|'r')
			case "$token" in
			    's') num=6 ;;
			    'r') num=5 ;;
			esac
			filter "$list" 'tmp=${line%$nl}' '|'
			IFS='|'
			set -- $filter
			unset IFS filter
			;;
		    'q')
			case "$token_q" in
			    'p')
				num=1
				filter "$info" 'tmp=$line' "$nl"
				IFS="$nl"
				set -- $filter
				unset IFS filter
				;;
			esac
			;;
		esac

                case $# in
                    0)
			num=1
			set -- 'no result'
			;;
                esac

		y=1 y2=$top cur=$1 ltype= msg="filter by *$ans*"
                redraw $num "$@"
            ;;
            \??)
                 set -- 'k - up' \
			'j - down' \
		        'l - right' \
		        'h - left' \
                        'g - go to top' \
                        'G - go to bottom' \
			's - search reference on Crossref by text' \
			'p - search reference on Crossref by PDF file' \
			'r - copy BibTeX entry from yoru $BIB' \
                        '/ - search in $BIB_PDF_PATH/<input>*' \
                        '? - show keybinds'
                num=1 y=1 y2=$top cur=$1 ltype= msg=keybinds token='?'
                redraw $num "$@"
            ;;
            q?) exit 0 ;;
            "$esc_c"*) esc=1 ;;
                 '[1') esc=2 ;;
                    *) esc=0 ;;
	esac
    done
}

main() {
    esc_c=$(printf '\033')
    bs_char=$(printf '\177')

    set -- $BIB_PDF_PATH/*.pdf
    cur=$1

    term_resize
    term_setup 1

    trap 'term_reset'  EXIT INT
    trap 'term_resize; term_setup $num; y=1 y2=$top; redraw $num "$@"' WINCH

    y=1 y2=$top
    redraw 1 "$@"

    get_os
    key "$@"
}

nl='
'
tab='	'
main "$@" >/dev/tty
